
all:

doc:
	@if [ ! -d "doc/html" ]; then mkdir -p doc/html; fi
	epydoc -v --output doc/html --html checkstyle/

check:
	@(cd test && ./check.sh)

clean:
	@rm -rf ./doc/

distclean: clean
	@find . -name '*.pyc' -exec rm -f {} +
	@find . -name '*.pyo' -exec rm -f {} +
	@find . -name '*~' -exec rm -f {} +
	@find . -name '__pycache__' -exec rm -rf {} +

help:
	@echo "Usage:"
	@echo "  make [all]\t\tNothing"
	@echo "  make doc\t\tBuild the documentation"
	@echo "  make check\t\tRun all the tests"
	@echo "  make clean\t\tRemove all files generated by make"
	@echo "  make distclean\t\tRemove all unnecessary files"
	@echo "  make help\t\tDisplay this help"

.PHONY:	doc clean help
